# Generated by Django 2.0.2 on 2018-03-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('imageurl', models.TextField()),
                ('siteurl', models.TextField()),
                ('sitename', models.CharField(max_length=100)),
            ],
        ),
    ]
