# Generated by Django 2.0.2 on 2018-05-01 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FolderAwe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('author', models.TextField()),
                ('imageurl', models.TextField(blank=True)),
                ('createdate', models.DateField(auto_now_add=True)),
                ('updatedate', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('imageurl', models.TextField(blank=True)),
                ('siteurl', models.TextField()),
                ('sitename', models.CharField(blank=True, max_length=100)),
                ('createdate', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='linkslist.Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='linkslist.FolderAwe'),
        ),
        migrations.AddField(
            model_name='category',
            name='parentcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linkslist.Category'),
        ),
    ]
