# Generated by Django 2.0.2 on 2018-03-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdata',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='linkdata',
            name='imageurl',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='linkdata',
            name='sitename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
