# Generated by Django 2.0.2 on 2018-03-03 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('linkslist', '0002_auto_20180301_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('parentcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkslist.Category')),
            ],
        ),
        migrations.AddField(
            model_name='linkdata',
            name='createdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkdata',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='linkslist.Category'),
        ),
    ]
