# Generated by Django 2.0.2 on 2018-03-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkslist', '0003_auto_20180303_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linkslist.Category'),
        ),
    ]
