# Generated by Django 2.0.2 on 2018-03-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkslist', '0005_auto_20180316_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='idlist',
            new_name='idfolder',
        ),
        migrations.RenameField(
            model_name='linkdata',
            old_name='idlist',
            new_name='idfolder',
        ),
    ]
