# Generated by Django 2.0.2 on 2018-03-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkslist', '0006_auto_20180316_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='idfolder',
            new_name='folder',
        ),
        migrations.RenameField(
            model_name='linkdata',
            old_name='idfolder',
            new_name='folder',
        ),
    ]
