# Generated by Django 2.0.2 on 2018-03-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkslist', '0007_auto_20180316_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idfolder', to='linkslist.FolderAwe'),
        ),
    ]
