# Generated by Django 2.0.2 on 2018-03-16 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkslist', '0008_auto_20180316_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdata',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='linkslist.FolderAwe'),
        ),
    ]
